# This is the name of the workflow that will appear in the "Actions" tab on GitHub.
name: Deploy to Shuttle

# This section defines the trigger for the workflow.
on:
  # Run this workflow on every push to the 'main' branch.
  push:
    branches:
      - main

# This section defines the job(s) to run.
jobs:
  deploy:
    # Use a standard Linux environment provided by GitHub.
    runs-on: ubuntu-latest

    steps:
      # Step 1: This checks out a copy of your repository's code.
      - name: Check out repository
        uses: actions/checkout@v4

      # (✓) NEW: This step caches your Rust dependencies and build artifacts.
      # This will make your deployments MUCH faster after the first run.
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Step 3: This uses the official Shuttle action to deploy your project.
      - name: Deploy to Shuttle
        uses: shuttle-hq/deploy-action@v2
        with:
          # This securely accesses the API key you stored in GitHub Secrets.
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          
          # (✓) IMPROVEMENT: The project ID is now also managed as a secret for better consistency.
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}